export type Company = {
  id: string;
  name: string;
  ceo: string;
  itemIntro: string;
};

export const companies: Company[] = [
  {
    id: "company-001",
    name: "오스㈜",
    ceo: "이응구",
    itemIntro: "반도체 공정의 핵심인 원자층 공정에서 최적 냉각 모듈 일체형 저온 스테이지",
  },
  {
    id: "company-002",
    name: "㈜엘엠엑스",
    ceo: "이현제 이철진",
    itemIntro: "차세대 의료 진단장치용 엑스선 튜브",
  },
  {
    id: "company-003",
    name: "㈜마이크로메디옴",
    ceo: "윤원석",
    itemIntro: "취약계층을 위한 환경AI 기반 디지털헬스케어 솔루션 K-DOLBOM",
  },
  {
    id: "company-004",
    name: "㈜악어에듀",
    ceo: "강태환",
    itemIntro: "SW·AI 교육 코스웨어 아케오",
  },
  {
    id: "company-005",
    name: "㈜피카부랩스",
    ceo: "서정환",
    itemIntro: "사내용 온디바이스 AI 문서 검색 어시스턴트 로컬독스",
  },
  {
    id: "company-006",
    name: "㈜컨시언스파트너스",
    ceo: "유승현",
    itemIntro: "AI 운영 리스크 관리 플랫폼",
  },
  {
    id: "company-007",
    name: "㈜나와",
    ceo: "서영호",
    itemIntro: "재활용을 혁신하는 분리수거기",
  },
  {
    id: "company-008",
    name: "㈜파이큐랩",
    ceo: "양태석",
    itemIntro: "비파괴 내부 검사 AO 홀로그래픽현미경",
  },
  {
    id: "company-009",
    name: "㈜더키퍼",
    ceo: "김도영",
    itemIntro: "AI 기반의 전기차 화재 예방 솔루션",
  },
  {
    id: "company-010",
    name: "㈜스밈팩토리",
    ceo: "임정동",
    itemIntro: "멀티모달 기반 온디바이스 시니어 헬스케어 추론 모델 채움핏",
  },
  {
    id: "company-011",
    name: "포스트얼라인",
    ceo: "김병수",
    itemIntro: "표준 치료 없는 희귀암을 위한 글로벌 의료진 대상 의사결정지원 LLM 플랫폼",
  },
  {
    id: "company-012",
    name: "마인드풀랩스㈜",
    ceo: "강호남",
    itemIntro: "심리상담 행정 완전 자동화 Multi-Agent AI SaaS",
  },
  {
    id: "company-013",
    name: "㈜스페이스점프",
    ceo: "배상일",
    itemIntro: "로컬 비즈니스를 혁신하는 AI 기반 사업 기자재 자동화 거래 솔루션 소상공간",
  },
  {
    id: "company-014",
    name: "㈜폰드메이커스",
    ceo: "박이래",
    itemIntro: "K-디지털 굿즈 마켓, 그랩뮤직",
  },
  {
    id: "company-015",
    name: "㈜고로켓컴퍼니",
    ceo: "유병욱",
    itemIntro: "건강 의사결정을 돕는 예방 디지털 헬스케어 서비스 팜픽",
  },
  {
    id: "company-016",
    name: "㈜스텔업",
    ceo: "오민지",
    itemIntro: "외국인 학습자를 위한 AI 기반 비즈니스 한국어 학습 솔루션 한글링",
  },
  {
    id: "company-017",
    name: "섬루션",
    ceo: "전성환",
    itemIntro: "친환경 AI 스마트 부표 솔루션",
  },
  {
    id: "company-018",
    name: "㈜아이앤그로쓰",
    ceo: "성지훈",
    itemIntro: "자체 기술로 원가절감한 중소기업용 Physical AI 맞춤형 솔루션",
  },
  {
    id: "company-019",
    name: "㈜휴스파인",
    ceo: "오세준",
    itemIntro: "AI 기반 가정용 척추감압 솔루션",
  },
  {
    id: "company-020",
    name: "㈜유니폭스",
    ceo: "황준선",
    itemIntro: "간편 나홀로 소송 간소화 시스템 참지마요",
  },
  {
    id: "company-021",
    name: "㈜한국정보통신과학기술",
    ceo: "서지안",
    itemIntro: "다국가 다단말 환경의 기업 고객을 위한 eSIM 기반 통합 통신 제어 및 관리 플랫폼 Telescale AI",
  },
  {
    id: "company-022",
    name: "㈜케이에이치에스이",
    ceo: "정세빈",
    itemIntro: "AI 안전관리·리스크판단 시스템 안전킹",
  },
  {
    id: "company-023",
    name: "㈜헤이트먼데이",
    ceo: "최원석",
    itemIntro: "이륜차 AI 진단 통합 플랫폼 서비스 두바키",
  },
  {
    id: "company-024",
    name: "페블즈㈜",
    ceo: "김두형",
    itemIntro: "인플루언서 기반의 AI 마케팅 에이전트 서비스 쇼키",
  },
  {
    id: "company-025",
    name: "㈜헬로프렌즈",
    ceo: "강동신",
    itemIntro: "RAG 기반 외국인 행정 지원 솔루션",
  },
  {
    id: "company-026",
    name: "㈜세이브프롬",
    ceo: "차명준",
    itemIntro: "2030 여성을 위한 안심 생활서비스 플랫폼 이거해줘",
  },
  {
    id: "company-027",
    name: "㈜퐁",
    ceo: "정보연",
    itemIntro: "AI를 활용한 마인드 웰니스 솔루션",
  },
  {
    id: "company-028",
    name: "AxonEQ",
    ceo: "이준호",
    itemIntro: "열화상 카메라 및 믹싱 공정 데이터를 융합한 Multi-modal AI 기반 슬러리 분석 솔루션",
  },
  {
    id: "company-029",
    name: "㈜에임즈미디어",
    ceo: "소휘수",
    itemIntro: "생성형 AI 기반 결손공간 복원·시나리오 합성 솔루션 AIMZLABS",
  },
  {
    id: "company-030",
    name: "㈜언박싱드림즈",
    ceo: "최성호",
    itemIntro: "AI 기반 맞춤 시니어펫 진료 및 장례 광고 솔루션 펫나잇",
  },
  {
    id: "company-031",
    name: "BioFrix",
    ceo: "박희등",
    itemIntro: "천연물 유래 생물막 저해제 기반 여드름 케어 제품",
  },
  {
    id: "company-032",
    name: "㈜오르빗코리아",
    ceo: "김민수",
    itemIntro: "글로벌 진출 D2C 브랜드를 위한 AI 기반 컨설팅펌 오르빗",
  },
  {
    id: "company-033",
    name: "㈜퍼슬리",
    ceo: "오상준 남궁현",
    itemIntro: "세대 암 환자와 가족을 위한 개인 의료기록 기반 AI 건강 비서 PERSLY",
  },
  {
    id: "company-034",
    name: "㈜테르밋",
    ceo: "김지성",
    itemIntro: "온라인 판매를 위한 마케팅 콘텐츠 디자인 AI 크리에이지",
  },
  {
    id: "company-035",
    name: "㈜오셜",
    ceo: "오수열",
    itemIntro: "의도 번역 AI Agent TransIntent",
  },
  {
    id: "company-036",
    name: "이퀵렌트",
    ceo: "김민준",
    itemIntro: "전동공구, 중장비 데이터 관리 및 매칭 서비스 쉬프툴",
  },
  {
    id: "company-037",
    name: "메디하이브",
    ceo: "조채은",
    itemIntro: "환자–의료진 양방향 니즈를 연결하는 AI 의료기록 요약·진료 지원 플랫폼 MediHive",
  },
  {
    id: "company-038",
    name: "K-HealthMatch",
    ceo: "김희중",
    itemIntro: "개인별 건강 위험도를 AI로 분석하여 맞춤형 디지털 헬스 기기와 앱을 연결해주는 정밀의학 기반 헬스케어 및 생체시그널 데이터 관리 서비스",
  },
  {
    id: "company-039",
    name: "㈜크로니카",
    ceo: "김재완",
    itemIntro: "버추얼 크리에이터·IP 육성 플랫폼 Studio Chronika",
  },
  {
    id: "company-040",
    name: "CogniLeap",
    ceo: "조성진",
    itemIntro: "기상·수문 원시 데이터를 자동 표준화하고 집단지성 검증을 통해 신뢰할 수 있는 데이터 자산으로 전환하는 데이터 자산화 허브",
  },
  {
    id: "company-041",
    name: "㈜로코코",
    ceo: "김민희",
    itemIntro: "글로벌 K-뷰티 빅데이터 분석을 통한 유럽 K-뷰티 온·오프라인 리테일 플랫폼 Lococo",
  },
  {
    id: "company-042",
    name: "㈜컬러루트",
    ceo: "김효정",
    itemIntro: "무슬림 히잡 착용자 특화 AI 비전 기반 퍼스널컬러 진단 및 AR 가상착용 콘텐츠 결합형 히잡·뷰티 커머스 플랫폼 마이누르",
  },
  {
    id: "company-043",
    name: "피어링",
    ceo: "송유정",
    itemIntro: "특수교육 코디네이터 AI SaaS",
  },
  {
    id: "company-044",
    name: "만동제과",
    ceo: "신주훈",
    itemIntro: "K뷰티 커머스 마케팅 플랫폼 Subak",
  },
  {
    id: "company-045",
    name: "조앤안",
    ceo: "안운장",
    itemIntro: "AI 크리에이티브 스튜디오 GESTEL",
  },
  {
    id: "company-046",
    name: "오늘은혜",
    ceo: "김주안",
    itemIntro: "오늘은혜·인생 시뮬레이션 AI 채팅 웹/앱 라이프어게인",
  },
  {
    id: "company-047",
    name: "Seed Wave",
    ceo: "이윤찬",
    itemIntro: "사막화 방지를 위한 다발적 식물 군집 형성 파종장치 Ecodrop",
  },
  {
    id: "company-048",
    name: "㈜루이스타",
    ceo: "JIA RUISI",
    itemIntro: "AI·빅데이터 기반 중화권 방한 고객 초개인화 매칭·수요 예측 플랫폼 RUISTAR ONE Data+AI",
  },
  {
    id: "company-049",
    name: "씨플립",
    ceo: "최희수",
    itemIntro: "AI 결제를 코인 뒤집는 것만큼 쉽게 만드는 C.Flip",
  },
];